### ISSUE TITLE
[Proposal] Use directly sentry external configuration

### ISSUE THREAD

**Issue by mathieutu** [yakovlev-alexey/keycloak-sentry-logger#2]
Hi,
Thanks for your great work.

By default, Sentry allows to be configured with environment variables.

<details>
<summary>See doc extracts ⬇️</summary>
<img width="779" alt="Screenshot 2023-02-24 at 21 14 24" src="https://user-images.githubusercontent.com/11351322/221286749-05362ea7-a31e-43b1-8d2b-46f2ddd2aaf8.png">
<img width="764" alt="Screenshot 2023-02-24 at 21 13 27" src="https://user-images.githubusercontent.com/11351322/221286774-2d0c7559-2d41-49c4-b120-af8326d7ef4f.png">
<img width="767" alt="Screenshot 2023-02-24 at 21 14 11" src="https://user-images.githubusercontent.com/11351322/221286790-7000d3c4-1780-4c07-974c-ca7de9a2724b.png">
</details>

However, this logic is [only handled](https://github.com/getsentry/sentry-java/blob/db5bd4eb7ce795ee335af91e09320780ce1d9d45/sentry/src/main/java/io/sentry/Sentry.java#L216-L218) in the `Sentry.init` function, that this package doesn't use (by creating a Hub manually).

Relying on this mechanism would all package users to easily provide their config to Sentry without rebuilding this package (ex: adding an environment by providing `SENTRY_ENVIRONMENT` to Keycloak).

Would you agree to merge a PR that updates the code to allow this feature?
- It would remove [the need to set the options manually](https://github.com/yakovlev-alexey/keycloak-sentry-logger/blob/52c1bd18008c924d0df482282f82eae6bb323638/src/main/java/dev/yakovlev_alexey/keycloak/events/SentryEventListenerFactory.java#L50-L52)
- It would force us to use the `Sentry.init` method instead of instancing manually a Hub. 
With that, we'd have two choices:
	- 1️⃣ Keep passing the hub to the EventListener (hub got with `Sentry.getCurrentHub()`)
	- 2️⃣ Use directly the static Sentry implementation (`Sentry.captureEvent` instead of `hub.captureEvent`).

I'd be personally in favour of 2️⃣, as it simplifies the code, and it's the Sentry standard and what is shown in the doc.
However, I'll follow your directive if you prefer 1️⃣.

I'd be glad to do the PR if you're OK with that (I've started and stopped, seeing the choices to do, and the architecture implication).

Thanks for your help,
Mathieu.

**Comment by yakovlev-alexey** [comment]
Hi Mathieu!

Getting rid of the manual option parsing would be great!

I think the reasoning behind passing a Hub instance instead of using the static interface directly was so that other plugins do not conflict with this one by using the same instance. But thinking about this now, I realise that environment variables are still the same and creating a Hub would not help much to avoid conflicts.

Still, injecting a Hub instance to the listener provides a cleaner interface in my opinion. And in a scenario where one actually has multiple instances of Sentry in their Keycloak application they will have an easier time configuring (or rather customising) this plugin. So I would go with the 1️⃣ option. And since the actual Sentry configuration will presumably be gone from `SentryConfiguration` interface it would make sense to rename this interface to `SentryEventListenerConfiguration`.

Looking forward to your PR! And thank you for your interest in improving this plugin.
